source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SCPageView_Example' do
  pod 'SCPageView', :path => '../'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.0'

  target 'SCPageView_Tests' do
    inherit! :search_paths


  end
end
